name: qa-site

on:
  pull_request:
    branches:
      - main
    paths:
      - 'module/site/**'

jobs:
  qa:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: |
          pnpm install
          pnpm site lint
          pnpm site build
